baseURL = "http://blog.ni4ai.org/"
#baseURL = "/"
languageCode = "en-us"
title = "NI4AI Blog"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-147537346-3"
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["assets/css/page.css"]
  favicon = ""
  description = "A blog for The National Infrastructure for Artificial Intelligence on the Electric Grid"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  recent_posts_number = 5

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "s3blog"
URL = "s3://blog.ni4ai.org?region=us-east-1"

[[deployment.matchers]]
# Cache static assets for 6 months and compress
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=15770000, no-transform, public"
gzip = true

[[deployment.matchers]]
# Cache images for 6 months but do not compress
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=15770000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Compress text files
pattern = "^.+\\.(html|xml|json)$"
gzip = true
